apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-k8s
  template:
    metadata:
      labels:
        app: go-k8s
    spec:
      containers:
      - name: go-k8s
        image: gcr.io/go-k8s-279400/go-k8s:1.0.0
        resources:
          limits:
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: go-k8s-app
  labels:
    app: go-k8s
spec:
  type: LoadBalancer
  selector:
    app: go-k8s
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 9090
      nodePort: 30003