apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-k8s
  template:
    metadata:
      labels:
        app: go-k8s
    spec:
      containers:
      - name: go-k8s
        image: zmalarcon/go-k8s:1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: go-k8s-app
  labels:
    app: go-k8s
spec:
  type: NodePort
  selector:
    app: go-k8s
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090